image: maven:3.6.3-jdk-13
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SONAR_HOST_URL: "http://sonar.visegue.se"
  GIT_DEPTH: 0

stages:
  - build
  - test
  - package
  - deploy

default:
  cache: &global_cache
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - .m2/repository/
      - target/

build:
  stage: build
  script:
    - mvn clean package -f pom.xml
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn test verify sonar:sonar -Dsonar.qualitygate.wait=true
    - cat target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>'
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - target/site/jacoco/
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

build:container:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

